config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "sites#homepage"

  resources :images
  resources :tags
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/image.rb
class Image < ApplicationRecord
  has_one_attached :file
  has_and_belongs_to_many :tags
  belongs_to :user

  after_commit :generate_tags, on: :create

  private

  def generate_tags
    return if self.file.blank?

    gemini_tags = GoogleVertexAi.get_tags_from_image(self.file.download, self.file.blob.content_type)

    if gemini_tags.present? && gemini_tags.is_a?(Array)
      gemini_tags.each do |tag|
        self.tags << Tag.find_or_create_by(name: tag)
      end
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :images
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.all
  end

  def show
    @image = Image.find(params[:id])
  end

  def new
    @image = Image.new
  end

  def create
    @image = current_user.images.new(image_params)
    if @image.save
      redirect_to @image, notice: 'Image was successfully uploaded.'
    else
      render :new
    end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_back_or_to images_path, notice: 'Image was successfully destroyed.'
  end

  private

  def image_params
    params.require(:image).permit(:title, :file)
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  skip_before_action :authenticate_user!
  def homepage
    if user_signed_in?
      redirect_to images_path
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.includes(:images).find(params[:id])
    @images = @tag.images
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = current_user.images.new(image_params)
    if @tag.save
      redirect_to images_path, notice: 'Image was successfully uploaded.'
    else
      render :new
    end
  end

  def destroy
    @tag = Image.find(params[:id])
    @tag.destroy
    redirect_to images_path, notice: 'Image was successfully destroyed.'
  end

  private

  def image_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when :notice then "alert alert-info"
    when :success then "alert alert-success"
    when :error then "alert alert-error"
    when :alert then "alert alert-error"
    end

  end
end

app/views/images/index.html.erb
<h1>Images</h1>
<%= link_to 'Upload an Image', new_image_path %>
<table>
  <thead>
        <tr>
            <th>Image</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
      <% @images.each do |image| %>
        <tr>
          <td><%= image.title %></td>
          <td>
            <%= link_to 'View', image_path(image) %>
            <%= link_to 'Delete', image_path(image), data: { turbo_method: :delete }%>
          </td>
        </tr>
      <% end %>
    </tbody>
</table>

app/views/images/new.html.erb
<h1>Upload an image</h1>

<%= form_with(model: @image) do |f| %>
  <%= f.label :title, 'Title' %>
  <%= f.text_field :title, placeholder: 'Please enter a title', required: true %>
  <%= f.file_field :file, required: true, accept: 'image/jpeg, image/png' %>
  <%= f.submit %>
<% end %>

app/views/images/show.html.erb
<h1>Images / <%= @image.title %></h1>

<div class="image-tags">
  <% @image.tags.each do |tag| %>
    <%= link_to tag.name, tag, class: 'image-tag' %>
  <% end %>
</div>

<%= link_to 'Edit', '#' %>
<%= link_to 'Delete', '#' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aisight</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
        <%= value %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/sites/homepage.html.erb
<% if !user_signed_in? %>
  <h1>Sign in to AiSight</h1>

  <%= form_with model: User.new, url: user_session_path do |f| %>
    <%= f.label :email, 'Email' %>
    <%= f.text_field :email %>
    <%= f.label :password, 'Password' %>
    <%= f.password_field :password %>
    <%= f.submit 'Sign In' %>
  <% end %>
<% end %>

app/views/tags/index.html.erb
<h1>Tags</h1>

<table>
  <thead>
    <tr>
      <th>Tag</th>
      <th>Total Images</th>
    </tr>
  </thead>
  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= tag.images.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tags/show.html.erb
<h1>Tags / <%= @tag.name %></h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tags</th>
      <th>Total Tags</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.title %></td>
        <td>
          <% image.tags.each do |tag| %>
            <%= link_to tag.name, tag %>
          <% end %>
        </td>
        <td><%= image.tags.count %></td>
        <td>
          <%= link_to 'View', image %>
          <%= link_to 'Delete', image, data: { turbo_method: :delete }%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>